[Feature] Issue - 192 / SMS
wanna-go-home/lens_review_server pull request #112
Opened 2021-03-16 13:53 UTC by yoowonyoung

- fix https://github.com/wanna-go-home/Issue/issues/192
- 일단 DB 만들기 전까진 홀드

2021-04-05 05:40 UTC, rlarlvy153 commented on src/main/java/com/springboot/intelllij/controller/UserController.java
> +                                  @RequestParam(value = "appHash") String appHash) {
안들어오면 어케됨

2021-04-05 05:41 UTC, rlarlvy153 commented on src/main/java/com/springboot/intelllij/controller/UserController.java
> +    public ResponseEntity checkAuthCode(@RequestParam(value = "requestId") Integer requestId,
카멜?

2021-04-05 05:42 UTC, rlarlvy153 commented on src/main/java/com/springboot/intelllij/domain/UserAuthEntity.java
> +    private boolean verified = false;
가입중간까지만 하고 끈놈은 유령회원?

2021-04-05 05:42 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/controller/UserController.java
> +                                  @RequestParam(value = "appHash") String appHash) {
앱해시? 폰넘? 어느쪽 안들어온놈?

2021-04-05 05:42 UTC, rlarlvy153 commented on src/main/resources/application.yml
> +  api-key: NCSOQKWAITYK3NUO
퍼블릭레포인데 여따박아도됨?

2021-04-05 05:43 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/controller/UserController.java
> +    public ResponseEntity checkAuthCode(@RequestParam(value = "requestId") Integer requestId,
authCode?

2021-04-05 05:44 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/domain/UserAuthEntity.java
> +    private boolean verified = false;
ㄴㄴ 이건 인증 기록만임. 최종 signUp전까지는 회원 데이터로는 추가 안되고, 인증 데이터만 추가됨

2021-04-05 05:45 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/controller/UserController.java
> +                                  @RequestParam(value = "appHash") String appHash) {
휴대폰 번호 클라에서 체크해주는거 아님?!

2021-04-05 05:54 UTC, yoowonyoung commented on src/main/resources/application.yml
> +  api-key: NCSOQKWAITYK3NUO
ㅋㅋㅋㅋㅋㅋ 숨겨야지...

2021-04-05 07:25 UTC, rlarlvy153 commented on src/main/java/com/springboot/intelllij/controller/UserController.java
> +                                  @RequestParam(value = "appHash") String appHash) {
앱해시

2021-04-05 07:26 UTC, rlarlvy153 requested changes
api key 제거후 ㄱ

2021-04-06 12:37 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/controller/UserController.java
> +                                  @RequestParam(value = "appHash") String appHash) {
디폴트값 넣엇음. 근데 앱해시 없으면 클라에서 인식 못하는거 아님?

2021-04-06 12:37 UTC, merged