Header Authorization
wanna-go-home/lens_review_server pull request #20
Opened 2020-10-05 11:55 UTC by yoowonyoung

- Header에 Authorization 추가
    + 해당 기능을 위해 login 기능 추가(/api/user/login)
    + login성공시 Response Header에 토큰이 발급됨(유효기간 1년)
    + API 호출시 Authorization Token이 없으면 unauthorized Error Response 

https://mangkyu.tistory.com/57

2020-10-05 12:23 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/config/CustomAuthenticationFilter.java
> +        authRequest = new UsernamePasswordAuthenticationToken(map.get("account"), map.get("pw"));
Request에서 헤더 까가지고 account / pw 를꺼내서 인증하는과정
로그인시 발생하는 이벤트

2020-10-05 12:23 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/config/CustomAuthenticationProvider.java
> +        if(!passwordEncoder.matches(userPw,account.getAccountPw())) {
저장된 암호화되어있는 pw와 입력받은 pw가 동일한지 확인

2020-10-05 12:23 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/config/CustomLoginSuccessHandler.java
> +        response.addHeader(AuthConstant.AUTH_HEADER,AuthConstant.TOKEN_TYPE + " " + token);
로그인 성공시 헤더에 token 정보 넣어서 반환

2020-10-05 12:23 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/config/JwtInterceptor.java
> +            if(TokenUtils.isValidToken(token))
토큰이 유효한지(올바른 토큰 / 유효기간 등) 검사

2020-10-05 12:23 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/config/SecurityConfig.java
> +        return new BCryptPasswordEncoder();
비번 암호화할때 쓰는놈

2020-10-05 12:23 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/config/SecurityConfig.java
> +        return new BCryptPasswordEncoder();
http://www.devkuma.com/books/pages/1124

2020-10-05 12:23 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/config/SecurityConfig.java
> +        return customAuthenticationFilter;
컨트롤러 구현 없이 필터를 통해서, 로그인 요청을 처리

2020-10-05 12:23 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/config/SwaggerConfig.java
> +                .globalOperationParameters(parameterList)
스웨거를 통해서도 Authorization 토큰을 입력 가능하게 해주는 부분
나중에 id / pw 혹은 토큰을 미리 입력해두는 방법으로 바꿀까 함
https://blog.naver.com/PostView.nhn?blogId=cutesboy3&logNo=221510400386&categoryNo=22&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=postView

2020-10-05 12:23 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/config/WebMvcConfig.java
> +                .addPathPatterns("/api/*");
/api 하위 모든 path에 대해서 인터셉터 추가

2020-10-05 12:23 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/controller/ErrorController.java
> +        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
인증 실패시 넘어오는 부분

2020-10-05 12:23 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/utils/TokenUtils.java
> +                .signWith(SignatureAlgorithm.HS256,createSigningKey());
HS256으로 인코딩한 JWT만듬

2020-10-22 13:56 UTC, zamonia500 approved these changes
사실 이해는 잘 못했지만 머지해야 할 때가 온 것 같음

2020-10-23 14:48 UTC, rlarlvy153 approved these changes

2020-10-23 14:50 UTC, rlarlvy153 commented
key : Authorization 
value : api token

토큰발급 방법등 api 정보점

2020-10-23 15:00 UTC, rlarlvy153 requested changes
회원가입도 붙여주십시오

2020-10-24 02:44 UTC, yoowonyoung commented
로그인 까지는 이미 구현 되어있음 ( id : admin / pw : admin )

<img width="1449" alt="스크린샷 2020-10-24 오전 11 22 43" src="https://user-images.githubusercontent.com/11551871/97065831-5a373f00-15eb-11eb-8866-62c5fae6aa81.png">

SWAGGER에는 이제 Authorization 이 추가되어 저부분을 추가해야만 API가 정상적으로 동작될것
( 안넣거나 잘못된걸 넣으면 401 UnAuthorized를 반환할것임 )

1. 로그인 방법 
<img width="1281" alt="스크린샷 2020-10-24 오전 11 33 15" src="https://user-images.githubusercontent.com/11551871/97066039-cd8d8080-15ec-11eb-85e0-f8a204132e5d.png">

- /apu/user/login 주소에 header에 account / pw ( admin / admin ) 을 입력해 POST 요청
- 200 OK 시 반환된 헤더에 Authorization 의 부분에 토큰이 발급됨 (ex> BEARER eyJyZWdEYXRlIjoxNjAzNTA1ODkwNTU2LCJ0eXBlIjoiSldUIiwiYWxnIjoiSFMyNTYifQ.eyJuaWNrbmFtZSI6ImFkbWluIiwiaWQiOiJhZG1pbiIsImV4cCI6MTYzNTA0MTg5MCwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20ifQ.dYi5wOqt7KN4lyCwKXEIm8zbKRvTG0B2T_cjlvyZkyM )
- **SWAGGER로는 확인 불가능 postman을 쓰셈** ( 스웨거에는 /api/user/login이 안보일것 - api를 따로 구현한것이 아니라 필터 기능을 이용해 만들엇기 때문에 - 이부분은 나중에 설명해줌 )

2. 로그인 이후 토큰 활용 방법
- SWAGGER 접속
- 이후 확인할 API에 Authrorization 부분을 넣지 않고 해보기 
    + 401 반환될것

- Authrorization 부분에 아까 받은 토큰을 넣어 ( BEARER 부분까지 포함 ) 요청
    + 200 OK 이후 정상적인 데이터 반환될것

2020-10-24 02:47 UTC, merged