Add POST api to insert post into free-board
wanna-go-home/lens_review_server pull request #9
Opened 2020-09-01 14:55 UTC by zamonia500

- `post`가 안먹길래 `getHttp().cors().and().csrf().disable();` 추가함
- users table 추가함
- free_board table 추가함

![스크린샷 2020-09-01 오후 11 54 41](https://user-images.githubusercontent.com/25953706/91867394-95358a00-ecae-11ea-9362-3e51d8687ea4.png)

2020-09-02 12:46 UTC, up0617 approved these changes
굿굿

2020-09-02 14:24 UTC, yoowonyoung requested changes
구조 잡고 갑시다~

2020-09-02 14:24 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/controller/RestController.java
> +        Object result = freeBoardRepository.findAll();
기존에 들가있는 서비스로 이전 부탁두림

2020-09-02 14:24 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/domain/UserEntity.java
> +@Table(name = "user", schema = "public")
schema는 shcema 기능이 있는 디비에서 스키마를 매핑할때 사용합니당
우리 스키마 씀?

2020-09-02 14:24 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/config/SecurityConfig.java
> +        getHttp().cors().and().csrf().disable();
음... 이부분은 좀 설명이 길어지는데,
먼저 Spring boot은 기본적으로 CSRF 에 관한 설정을 갖고있음(https://cheese10yun.github.io/spring-csrf/ 참고)
그래서 이렇게 하면은 CSRF 관련 설정들이 꺼지게 됨.
우리가 지금 토근 발급 관련 기능들이 없고, 클라에서도 토큰을 넣어서 리퀘스트를 날리지 않기 때문에,
어쩔수 없이 이렇게 가는게 현재 상황에서는 맞긴 하겠지만 실제로는 이렇게 하면 안됨(보안상의 이슈)
지금은 그냥 굴렁쇠를 만드는 과정이기 때문에 넘어가지만, 이부분은 이슈로 남겨두고 추후에 보안 관련 기능들을 추가하고 변경합시다

2020-09-02 14:26 UTC, yoowonyoung commented
머지 컨플릭도 해결 부탁두림

2020-09-02 14:28 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/config/SecurityConfig.java
> +        getHttp().cors().and().csrf().disable();
https://github.com/wanna-go-home/lens_review_server/issues/10 로 이슈 남겨두었음
Known issue로 들고가면서 추후 기능보강후 CSRF는 enable 하는걸로 합시다

2020-09-05 05:09 UTC, zamonia500 commented on src/main/java/com/springboot/intelllij/domain/UserEntity.java
> +@Table(name = "user", schema = "public")
user라는 table이 postgreSQL 내부에서 사용되고 있어서
어느쪽 user라는 걸 분명히 명시해야 했음

2020-09-05 05:09 UTC, zamonia500 commented on src/main/java/com/springboot/intelllij/config/SecurityConfig.java
> +        getHttp().cors().and().csrf().disable();
ㅇㅋㅋ

2020-09-05 05:36 UTC, zamonia500 commented on src/main/java/com/springboot/intelllij/controller/RestController.java
> +        Object result = freeBoardRepository.findAll();
일단 갯수 겁나 적어서  Lens 컨트롤러 쪽으로 밀가놓음

2020-09-05 06:12 UTC, yoowonyoung reviewed
코멘트확인점

2020-09-05 06:12 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/controller/LensInfoController.java
> +        Object result = userRepo.findAll();
여기는 LensInfoController니깐, LensInfo에 관련된 처리를 하는 곳이여야 합니다.
User를 반환하는건 UserController로 독립 부탁두림
거기에서도 컨트롤러에서 Repository로 바로 접근하지말고,
UserServicer같은걸 하나 만들어서 서비스를 호출하도록 하고,
서비스 내부에서 Repository를 접근하도록 하죠

2020-09-05 06:12 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/controller/LensInfoController.java
> +        freeBoardRepository.save(freeBoard);
여기도 동일. 
BoardController로 만들어둬서 나중에 거기에서 자유게시판이랑 리뷰 게시판을 같이 컨트롤 하도록 하게 독립 부탁드림.
그다음에 서비스는 일단 FreeBoardService정도로 하나 만들어서 붙여주도록 하고, 
추후에 리뷰용 ReviewBoardService만들다가 공통되는거 많이보이면 뽑아서 합치는걸로 가죠

2020-09-05 06:12 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/domain/UserEntity.java
> +@Table(name = "user", schema = "public")
그렇다면 Table의 이름을 바꾸는것도 한번 고려해봄직합니다

2020-09-05 06:16 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/controller/LensInfoController.java
> +    public Object getFreeBoard() {
여기 이름은 getFreeBoard인데 내용은 getAll이네?
요구사항에 부합하지 않는듯.

2020-09-05 10:26 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/controller/UserController.java
> +@RestController
@zamonia500 떼껄룩

2020-09-05 10:28 UTC, yoowonyoung commented on src/main/java/com/springboot/intelllij/controller/UserController.java
> +@RestController
Controller vs RestController
https://doublesprogramming.tistory.com/105
FYI

2020-09-05 10:40 UTC, yoowonyoung approved these changes
고생하셧음둥 👍

2020-09-05 10:43 UTC, merged